[package]
name = "nextsyncengine"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.7", features = ["blocking", "json"] }
base64 = "0.22.1"
dotenv = "0.15.0"
chrono = "0.4.38"

[profile.release]
lto = true
