name: Build Binaries
on: [push, pull_request]

jobs:
  test:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test --all-features
  build:
    name: Build for Windows and Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          target: "x86_64-unknown-linux-gnu, x86_64-pc-windows-gnu"

      # Build for Linux
      - name: Build for Linux
        run: cargo build --target x86_64-unkown-linux-gnu --release
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: nextsyncengine
          path: target/release/nextsyncengine

      # Build for Windows
      - name: Build for Windows
        run: cargo build --target x86_64-pc-windows-gnu  --release
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: nextsyncengine
          path: target/x86_64-pc-windows-gnu/release/nextsyncengine.exe
